### ISSUE TITLE
Clarifications

### ISSUE THREAD

**Issue by HeChengHui** [Vagver/3DGazeNet#2]
Hello @Vagver, thank you for your work! I have a few questions to clarify.

1) what is the difference between this [inference](https://github.com/Vagver/3DGazeNet/blob/main/inference.py) script and this [inference](https://github.com/Vagver/3DGazeNet/blob/main/demo/inference.py) script? 
2) Do i only need to do [preprocessing](https://github.com/Vagver/3DGazeNet?tab=readme-ov-file#inference) for images? since it is not mentioned in the demo folder.
3) Is the method implemented by [Insightface](https://github.com/deepinsight/insightface/tree/master/reconstruction/gaze) the same as this?

**Comment by eververas** [comment]
Hello HeChengHui,

1. The first inference script you mention is about performing inference on a set of images and store the results, while the second one is in essence a demo which can run directly on videos.
2. Demo does the preprocessing in the FacePredictor/GazePredictor classes.
3.  The method by insightface is the same.

Let me know if the above are not clear enough.

**Comment by HeChengHui** [comment]
@Vagver 

3. Is the performance of both implementation the same as well? I see that yours is more recently updated. 

I have tried to run the demo inference but there seems to be a mismatched of model?
`infer_res34_x128_xgz.yaml` loads `'data/res18_x128_vert_xgz.pth'` but the [link](https://drive.google.com/file/d/13Xw1Dx49oJ45TztACz_5fwy38cwvXMdD/view) provided is `res34_x128_vert_xgz`. Changing the name in the config causes an error: "Unexpected key(s) in state_dict:"

**Comment by eververas** [comment]
@HeChengHui 

The links provided have been currently tested for the inference.py and test.py scripts in the root dir of the repo. The demo code will be updated soon.

The models provided by insightface have similar performance, but will be updated soon, too.

**Comment by Echo-jyt** [comment]
> @Vagver
> 
> 3. Is the performance of both implementation the same as well? I see that yours is more recently updated.
> 
> I have tried to run the demo inference but there seems to be a mismatched of model? `infer_res34_x128_xgz.yaml` loads `'data/res18_x128_vert_xgz.pth'` but the [link](https://drive.google.com/file/d/13Xw1Dx49oJ45TztACz_5fwy38cwvXMdD/view) provided is `res34_x128_vert_xgz`. Changing the name in the config causes an error: "Unexpected key(s) in state_dict:"

Hi, Did you get `data/res18_x128_vert_xgz.pth`?

**Comment by HeChengHui** [comment]
@Echo-jyt 
Nope. I am using the InsughtFace version. Have yet to check this repo for any updates.

**Comment by Echo-jyt** [comment]
> @Echo-jyt Nope. I am using the InsughtFace version. Have yet to check this repo for any updates.

Can InsightFace run directly on video?

**Comment by HeChengHui** [comment]
@Echo-jyt 
Dont think so. Frames.

**Comment by Echo-jyt** [comment]
> @Echo-jyt Dont think so. Frames.

OK , fine.Thanks!
