### ISSUE TITLE
Important files missing

### ISSUE THREAD

**Issue by zhaishuyan** [Vagver/3DGazeNet#3]
@Vagver, thank you for your work!

I have noticed that some crucial files are missing when running the code. The specific files are as follows:

xgaze/lms68_3D_all.pkl and xgaze/lms8_all.pkl mentioned in xgaze_preprocess.py.
mpiiface/lms68_3D_all.pkl and mpiiface/lms8_all.pkl mentioned in mpiiface_preprocess.py.
gaze360/lms68_3D_wbb.pkl, lms68_3D_wobb.pkl, lms8_all.pkl, paths_train_hp90.txt, and paths_test_hp90.txt mentioned in gaze360_preprocess.py.

Could you kindly provide the code for generating these files or provide detailed information about the data so that I can generate these files myself?

**Comment by eververas** [comment]
Hello @zhaishuyan,

Thank you for your interest in our work. We will provide download links for the files you mention soon. 

For the time being you could employ the scripts that we already provide to generate the files. The “lms68_3D_all.pkl” files can be extracted using the “tools/preprocess_inference.py script” or your own 3D face landmarks localization algorithm. The “lms8_all.pkl” files can be generated by running the “inference.py” script on your images, using the provided checkpoint.

**Comment by zhaishuyan** [comment]
@Vagver Thank you for your tips. I have generated "lms68_3D_all.pkl" for the ETH-XGaze dataset using the "tools/preprocess_inference.py" script. However, this file is only suitable for the inference process and does not contain gaze data. I have noticed that the training set of the ETH-XGaze dataset does not provide the 3D gaze vectors, but they are required for training. Can you please guide me on how to calculate the 3D gaze vectors from the pitchyaw angles?

**Comment by neverstoplearn** [comment]
> Hello [@zhaishuyan](https://github.com/zhaishuyan),
> 
> Thank you for your interest in our work. We will provide download links for the files you mention soon.
> 
> For the time being you could employ the scripts that we already provide to generate the files. The “lms68_3D_all.pkl” files can be extracted using the “tools/preprocess_inference.py script” or your own 3D face landmarks localization algorithm. The “lms8_all.pkl” files can be generated by running the “inference.py” script on your images, using the provided checkpoint.

when will the files download links will provide?
