### ISSUE TITLE
some files are missing

### ISSUE THREAD

**Issue by ISCo9248** [Vagver/3DGazeNet#4]
Hi Vagver, thank you for your open source project
I was missing some key files while running the code. The detailed documents are as follows:
 
xgaze/lms68_3D_all.pkl and xgaze/lms8_all.pkl as mentioned in xgaze_preprocess.py.
mpiiface/lms68_3D_all.pkl and mpiiface/lms8_all.pkl as mentioned in mpiiface_preprocess.py.
Gaze360/lms68_3D_wbb.pkl, lms68_3D_wobb.pkl, lms8_all.pkl, paths_train_hp90.txt and paths_test_hp90.txt are available in gaze360_preprocess.py.
 
Are these key files generated by script or in another specific way? Thank you very much

**Comment by eververas** [comment]
Hello @ISCo9248 ,

Thank you for your interest in our work. We will provide download links for the files you mention soon. 

For the time being you could employ the scripts that we already provide to generate the files. The “lms68_3D_all.pkl” files can be extracted using the “tools/preprocess_inference.py script” or your own 3D face landmarks localization algorithm. The “lms8_all.pkl” files can be generated by running the “inference.py” script on your images, using the provided checkpoint.
